### ISSUE TITLE
Unity iOS 2022.3.0

### ISSUE THREAD

**Issue by yosun** [voxell-tech/UnityNLP#10]
Sample scene keeps crashing on play.

**Comment by nixonyh** [comment]
Is there a log file that we can look at? Thanks

**Comment by yosun** [comment]
```
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[485/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.EditorCoroutines.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.EditorCoroutines.Editor.dll, with 123 defines and 236 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[486/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.Burst.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.Burst.Editor.dll, with 123 defines and 237 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[487/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/VX.Util.Tests.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/VX.Util.Tests.Editor.dll, with 123 defines and 229 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[488/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/VX.Util.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/VX.Util.Editor.dll, with 123 defines and 237 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[489/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.VisualScripting.Core.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.VisualScripting.Core.Editor.dll, with 123 defines and 237 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[490/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.VisualScripting.Shared.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.VisualScripting.Shared.Editor.dll, with 123 defines and 242 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[491/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.Collections.DocCodeSamples.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.Collections.DocCodeSamples.dll, with 123 defines and 237 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[492/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.PlasticSCM.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.PlasticSCM.Editor.dll, with 123 defines and 226 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[493/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.Jobs.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.Jobs.Editor.dll, with 123 defines and 237 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[494/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.Settings.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.Settings.Editor.dll, with 123 defines and 236 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[495/536    0s] CopyFiles Library/ScriptAssemblies/Unity.TextMeshPro.dll
[496/536    0s] CopyFiles Library/ScriptAssemblies/VX.NLP.Runtime.VoxellNLP.dll
[497/536    0s] CopyFiles Library/ScriptAssemblies/VX.AI.Runtime.BigtreeAlgorithm.dll
[498/536    0s] CopyFiles Library/ScriptAssemblies/UnityEngine.UI.dll
[499/536    0s] CopyFiles Library/ScriptAssemblies/VX.NLP.Runtime.SharpEntropy.dll
[500/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.Core.dll
[501/536    0s] CopyFiles Library/ScriptAssemblies/VX.Util.Runtime.dll
[502/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.State.dll
[503/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Burst.dll
[504/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Timeline.dll
[505/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Jobs.dll
[506/536    0s] CopyFiles Library/ScriptAssemblies/VX.NLP.Runtime.SharpWordNet.dll
[507/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.Flow.dll
[508/536    0s] CopyFiles Library/ScriptAssemblies/VX.NLP.Runtime.dll
[509/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Settings.Editor.pdb
[510/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Settings.Editor.dll
[511/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Jobs.Editor.pdb
[512/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Jobs.Editor.dll
[513/536    0s] CopyFiles Library/ScriptAssemblies/Unity.PlasticSCM.Editor.dll
[514/536    0s] CopyFiles Library/ScriptAssemblies/Unity.PlasticSCM.Editor.pdb
[515/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Collections.DocCodeSamples.dll
[516/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Collections.DocCodeSamples.pdb
[517/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.Shared.Editor.pdb
[518/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.Shared.Editor.dll
[519/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.Core.Editor.dll
[520/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.Core.Editor.pdb
[521/536    0s] CopyFiles Library/ScriptAssemblies/VX.Util.Editor.pdb
[522/536    0s] CopyFiles Library/ScriptAssemblies/VX.Util.Editor.dll
[523/536    0s] CopyFiles Library/ScriptAssemblies/VX.Util.Tests.Editor.dll
[524/536    0s] CopyFiles Library/ScriptAssemblies/VX.Util.Tests.Editor.pdb
[525/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/UnityEditor.UI.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/UnityEditor.UI.dll, with 126 defines and 235 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[526/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Burst.Editor.dll
[527/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Burst.Editor.pdb
[528/536    0s] CopyFiles Library/ScriptAssemblies/Unity.EditorCoroutines.Editor.pdb
[529/536    0s] CopyFiles Library/ScriptAssemblies/Unity.EditorCoroutines.Editor.dll
[530/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.Flow.Editor.dll
[531/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.Flow.Editor.pdb
[532/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.SettingsProvider.Editor.dll
[533/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.SettingsProvider.Editor.pdb
[534/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Collections.BurstCompatibilityGen.dll
[535/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Collections.BurstCompatibilityGen.pdb
[536/536    0s] CopyFiles Library/ScriptAssemblies/Unity.TextMeshPro.Editor.dll
[537/536    0s] CopyFiles Library/ScriptAssemblies/Unity.TextMeshPro.Editor.pdb
[538/536    0s] CopyFiles Library/ScriptAssemblies/Unity.TextMeshPro.pdb
[539/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Mathematics.Editor.dll
[540/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Mathematics.Editor.pdb
[541/536    0s] CopyFiles Library/ScriptAssemblies/Unity.TestTools.CodeCoverage.Editor.OpenCover.Model.dll
[542/536    0s] CopyFiles Library/ScriptAssemblies/UnityEditor.UI.pdb
[543/536    0s] CopyFiles Library/ScriptAssemblies/UnityEditor.UI.dll
[544/536    0s] CopyFiles Library/ScriptAssemblies/Unity.TestTools.CodeCoverage.Editor.OpenCover.Model.pdb
[545/536    0s] CopyFiles Library/ScriptAssemblies/VX.NLP.Runtime.pdb
[546/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.State.pdb
[547/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Timeline.pdb
[548/536    0s] CopyFiles Library/ScriptAssemblies/VX.Util.Runtime.pdb
[549/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Burst.pdb
[550/536    0s] CopyFiles Library/ScriptAssemblies/VX.AI.Runtime.BigtreeAlgorithm.pdb
[551/536    0s] CopyFiles Library/ScriptAssemblies/VX.NLP.Runtime.SharpWordNet.pdb
[552/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Jobs.pdb
[553/536    0s] CopyFiles Library/ScriptAssemblies/VX.NLP.Runtime.VoxellNLP.pdb
[554/536    0s] CopyFiles Library/ScriptAssemblies/VX.NLP.Runtime.SharpEntropy.pdb
[555/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.Core.pdb
[556/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.Flow.pdb
[557/536    0s] CopyFiles Library/ScriptAssemblies/UnityEngine.UI.pdb
[558/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.TestTools.CodeCoverage.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.TestTools.CodeCoverage.Editor.dll, with 127 defines and 228 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[559/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.Timeline.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.Timeline.Editor.dll, with 124 defines and 237 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[560/536    0s] CopyFiles Library/ScriptAssemblies/Unity.TestTools.CodeCoverage.Editor.pdb
[561/536    0s] CopyFiles Library/ScriptAssemblies/Unity.TestTools.CodeCoverage.Editor.dll
[562/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Timeline.Editor.pdb
[563/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Timeline.Editor.dll
[564/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.CollabProxy.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.CollabProxy.Editor.dll, with 123 defines and 237 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[565/536    0s] CopyFiles Library/ScriptAssemblies/Unity.CollabProxy.Editor.dll
[566/536    0s] CopyFiles Library/ScriptAssemblies/Unity.CollabProxy.Editor.pdb
[567/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.VisualScripting.State.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.VisualScripting.State.Editor.dll, with 123 defines and 241 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[568/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.State.Editor.pdb
[569/536    0s] CopyFiles Library/ScriptAssemblies/Unity.VisualScripting.State.Editor.dll
[570/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.Performance.Profile-Analyzer.Editor.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.Performance.Profile-Analyzer.Editor.dll, with 123 defines and 236 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[571/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Performance.Profile-Analyzer.Editor.pdb
[572/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Performance.Profile-Analyzer.Editor.dll
[573/536    0s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.TestTools.CodeCoverage.Editor.OpenCover.Mono.Reflection.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.TestTools.CodeCoverage.Editor.OpenCover.Mono.Reflection.dll, with 123 defines and 236 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[574/536    0s] CopyFiles Library/ScriptAssemblies/Unity.TestTools.CodeCoverage.Editor.OpenCover.Mono.Reflection.pdb
[575/536    0s] CopyFiles Library/ScriptAssemblies/Unity.TestTools.CodeCoverage.Editor.OpenCover.Mono.Reflection.dll
[576/536    1s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.Mathematics.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.Mathematics.dll, with 122 defines and 229 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[577/536    1s] ILPostProcess Library/Bee/artifacts/900b0aE.dag/post-processed/Unity.Collections.dll (+pdb)
Processing assembly Library/Bee/artifacts/900b0aE.dag/Unity.Collections.dll, with 122 defines and 231 references
processors: Unity.Jobs.CodeGen.JobsILPostProcessors, zzzUnity.Burst.CodeGen.BurstILPostProcessor
running Unity.Jobs.CodeGen.JobsILPostProcessors
running zzzUnity.Burst.CodeGen.BurstILPostProcessor
[578/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Mathematics.pdb
[579/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Mathematics.dll
[580/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Collections.dll
[581/536    0s] CopyFiles Library/ScriptAssemblies/Unity.Collections.pdb
*** Tundra build success (3.48 seconds), 382 items updated, 536 evaluated
Total cache size 268013168
Total cache size after purge 268013168
Reloading assemblies after finishing script compilation.
Reloading assemblies after forced synchronous recompile.
Begin MonoManager ReloadAssembly
Symbol file LoadedFromMemory doesn't match image /Users/mbp16_2022_m1max/MyTests/unitynlp/UnityNLP/Library/PackageCache/com.unity.visualscripting@1.8.0/Editor/VisualScripting.Core/Dependencies/YamlDotNet/Unity.VisualScripting.YamlDotNet.dll
Symbol file LoadedFromMemory doesn't match image /Users/mbp16_2022_m1max/MyTests/unitynlp/UnityNLP/Library/PackageCache/com.unity.visualscripting@1.8.0/Editor/VisualScripting.Core/Dependencies/DotNetZip/Unity.VisualScripting.IonicZip.dll
Symbol file LoadedFromMemory is not a mono symbol file
- Loaded All Assemblies, in  0.832 seconds
Refreshing native plugins compatible for Editor in 0.30 ms, found 2 plugins.
mono_class_from_mono_type_internal: implement me 0x00

* Assertion: should not be reached at class.c:2214

Obtained 53 stack frames.
#0  0x000001c242ad78 in __pthread_kill
#1  0xac3e0001c239a340 in abort
#2  0xe85f0002b88a01f4 in monoeg_g_printv
#3  0x000002b888560c in mono_log_write_logfile
#4  0x000002b88a040c in monoeg_g_logv_nofree
#5  0x000002b88a04c8 in monoeg_assertion_message
#6  0x000002b88a0528 in monoeg_log_default_handler
#7  0x000002b87aa200 in mono_class_from_mono_type_internal
#8  0x000002b8715fe0 in inflate_info
#9  0x000002b8714be0 in instantiate_info
#10 0x000002b8711cc0 in fill_runtime_generic_context
#11 0x000002b870d008 in mono_rgctx_lazy_fetch_trampoline
#12 0x00000156f908fc in (Unknown)
#13 0x0000031e2d7588 in  UnityEditor.PackageManager.UI.Internal.UpmBaseOperation`1<T_REF>:.ctor () [{0x2bfa661f0} + 0xf8] [/Users/bokken/build/output/unity/unity/Modules/PackageManagerUI/Editor/Services/Upm/UpmBaseOperation.cs :: 84u] (0x31e2d7490 0x31e2d7c3c) [0x167242a80 - Unity Child Domain]
#14 0x0000031e2d7434 in  UnityEditor.PackageManager.UI.Internal.UpmSearchOperation:.ctor () [{0x158577058} + 0x14]  (0x31e2d7420 0x31e2d7440) [0x167242a80 - Unity Child Domain]
#15 0x00000312f122b0 in  (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr) [{0x1577c1c00} + 0x70]  (0x312f12240 0x312f1234c) [0x167242a80 - Unity Child Domain]
#16 0x000002b86954f0 in mono_jit_runtime_invoke
#17 0x000002b881b594 in do_runtime_invoke
#18 0x000002b881b4b4 in mono_runtime_invoke
#19 0x0000010572295c in mono_runtime_invoke_profiled(MonoMethod*, ScriptingObjectPtr, void**, MonoException**, MonoClass*)
#20 0x00000105722800 in mono_runtime_object_init_exception(ScriptingObjectPtr, ScriptingCtorCache*, MonoException**)
#21 0x00000105722a88 in mono_runtime_object_init_log_exception(ScriptingObjectPtr, ScriptingCtorCache*)
#22 0x00000105796134 in GetOrCreateObjectStoredInField(ScriptingFieldPtr, GeneralMonoObject&, bool)
#23 0x000001057cc7a4 in void Transfer_ManagedObject<SafeBinaryRead, false>(SerializationCommandArguments const&, RuntimeSerializationCommandInfo&)
#24 0x000001057cc8d4 in void Transfer_ManagedObject<SafeBinaryRead, false>(SerializationCommandArguments const&, RuntimeSerializationCommandInfo&)
#25 0x0000010573bd4c in void TransferScriptingObject<SafeBinaryRead>(SafeBinaryRead&, ScriptingObjectPtr, ScriptingClassPtr, SerializationCache::Data*&)::'lambda'(bool, bool)::operator()(bool, bool) const
#26 0x0000010573bb68 in void TransferScriptingObject<SafeBinaryRead>(SafeBinaryRead&, ScriptingObjectPtr, ScriptingClassPtr, SerializationCache::Data*&)
#27 0x0000010573b68c in void SerializableManagedRefTransfer::TransferScriptingObjectWithSerializedRefSupport<SafeBinaryRead>(Object*, SerializableManagedRef&, SafeBinaryRead&)
#28 0x0000010574dc50 in SerializableManagedRefTransfer::TransferSafeBinaryInstanceOnly(Object*, SerializableManagedRef&, BackupState*, TransferInstructionFlags)
#29 0x0000010574d758 in void SerializableManagedRefTransfer::RestoreBackupImpl<SerializableManagedRefBackupGenerator>(Object*, SerializableManagedRef&, TransferInstructionFlags)
#30 0x0000010581b908 in SerializableManagedRefsUtilities::RestoreBackups(DomainReloadingData const&)
#31 0x00000105732588 in MonoManager::FinalizeReload()
#32 0x00000106a6c214 in ScriptingInitializer::FinalizeReload()
#33 0x00000106b03c38 in RefreshInternalV2(AssetDatabase::UpdateAssetOptions, ScanFilter const&, InternalRefreshFlagsV2)
#34 0x00000106ae2484 in StopAssetImportingV2Internal(AssetDatabase::UpdateAssetOptions, InternalRefreshFlagsV2, ScanFilter const*, char const*)
#35 0x000001062f6cec in Application::TickTimer()
#36 0x0000010759ce34 in -[EditorApplication TickTimer]
#37 0x000001c34538e0 in __NSFireTimer
#38 0xcb300001c254789c in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
#39 0x460a0001c2547484 in __CFRunLoopDoTimer
#40 0x8f6e0001c2546f0c in __CFRunLoopDoTimers
#41 0x6a7c0001c252b984 in __CFRunLoopRun
#42 0xf9430001c252aa54 in CFRunLoopRunSpecific
#43 0x94248001cb16f338 in RunCurrentEventLoopInMode
#44 0x2b3f0001cb16efc4 in ReceiveNextEventCommon
#45 0xcb338001cb16ee68 in _BlockUntilNextEventMatchingListInModeWithFilter
#46 0x967b8001c50934b8 in _DPSNextEvent
#47 0x3c218001c5091db0 in -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
#48 0x78278001c5083f7c in -[NSApplication run]
#49 0x24288001c5055698 in NSApplicationMain
#50 0xf0760001075b5540 in EditorMain(int, char const**)
#51 0x000001075b587c in main
#52 0x0000010ada508c in (Unknown)
Launching bug reporter
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
[40m[32minfo[39m[22m[49m: Unity.ILPP.Runner.PostProcessingAssemblyLoadContext[0]
      ALC ILPP context 3 is unloading

```

**Comment by yosun** [comment]
Just repro on empty project with only UnityNLP and  its libraries installed. No Samples Imported. 
Switch to Unity iOS and editor crashes immediately

**Comment by yosun** [comment]
actually crashes upon switching to .net 4

which version of unity has this been tested to work? is it totally borked on unity 2022

**Comment by nixonyh** [comment]
hmm I think it is the .net 4 problem, I think we will need to port this back to .net 2.1...

**Comment by nixonyh** [comment]
.net 4 does not work well with unity DOTS packages especially the Entities package
